### ISSUE TITLE
为什么auuc波动这么大呢？

### ISSUE THREAD

**Issue by longweiwei** [kailiang-zhong/DESCN#2]
作者，您好，我运行了仓库中的代码，发现了AUUC波动很大，跟你贴出的jupyter中的出现的现象是一样的，请问造成这个现象的原因有哪些呢。
另外就是发现x-network比descn要好，根据jupyter中运行descn的超参数配置，AUUC为：0.031541，可能的原因在哪呢。

**Comment by kailiang-zhong** [comment]
第一个问题，关于auuc波动大，我认为主要是因为
1. treatment effect 信号本身比较弱（可[参见data](https://github.com/kailiang-zhong/DESCN/tree/main/data)），模型参数收敛时，预测值稍有一点变动，对序的影响产生波动，从而导致AUUC的波动。
2. 为了增强评估可靠性，我们做了多次重复实验，**每次实验都是独立重复采样，即每次实验的训练集不完全相同**，这也会引入AUUC的波动因素。

第二个问题，可能是因为环境不太一样？或者检查下配置是否有误？ 超参配置放在[这里](https://github.com/kailiang-zhong/DESCN/tree/main/conf4models/lzd_real_data)。 🤔

**Comment by longweiwei** [comment]
好的，感谢回复哈

**Comment by henryhuanghenry** [comment]
> 作者，您好，我运行了仓库中的代码，发现了AUUC波动很大，跟你贴出的jupyter中的出现的现象是一样的，请问造成这个现象的原因有哪些呢。 另外就是发现x-network比descn要好，根据jupyter中运行descn的超参数配置，AUUC为：0.031541，可能的原因在哪呢。
@longweiwei 
Hello~ 请问您后来有把AUUC调上去嘛？我使用仓库的配置，DESCN训练出来的也是差不多0.0317，X-network在0.030左右
